<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RescueTube.Domain\RescueTube.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Hangfire" Version="1.8.20" />
        <PackageReference Include="Hangfire.PostgreSql" Version="1.20.12" />
        <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="9.0.8" />
        <PackageReference Include="MediatR" Version="[12.5.0]" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.7" />
        <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.7" />
        <PackageReference Include="Riok.Mapperly" Version="4.2.1" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.10" />
    </ItemGroup>
</Project>
