<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0"/>
        <ProjectReference Remove="$(SolutionRoot)\RescueTube.Analyzers\RescueTube.Analyzers.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
      <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
    </ItemGroup>

</Project>
