<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\RescueTube.Core\RescueTube.Core.csproj" />
      <ProjectReference Include="..\RescueTube.Domain\RescueTube.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="9.0.8" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.10" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.10" />
      <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="9.0.10" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.10" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.10" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.10" />
    </ItemGroup>


</Project>
