<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="9.10.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.1.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.0.1" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp" Version="1.0.17">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.7.0" />
    <PackageReference Include="TUnit" Version="0.73.19" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RescueTube.Core\RescueTube.Core.csproj" />
    <ProjectReference Include="..\..\RescueTube.DAL.EF.Postgres\RescueTube.DAL.EF.Postgres.csproj" />
    <ProjectReference Include="..\..\RescueTube.YouTube\RescueTube.YouTube.csproj" />
  </ItemGroup>

</Project>
