using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace RescueTube.SourceGeneration;

[Generator(LanguageNames.CSharp)]
public class PartialGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classesToGenerate = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                PartialAttributeFullTypeName,
                predicate: static (_, _) => true,
                transform: GetClassToGenerate)
            .Where(static x => x is not null);

        context.RegisterSourceOutput(classesToGenerate, Execute);
    }

    private const string PartialAttributeFullTypeName = "RescueTube.Core.SourceGeneration.PartialAttribute`1";

    private static PartialClassToGenerate? GetClassToGenerate(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.TargetNode);

        if (symbol is not INamedTypeSymbol { TypeKind: TypeKind.Class } targetSymbol)
        {
            // Something went wrong?
            return null;
        }

        var sourceTypeProperties = targetSymbol.GetAttributes()
            .Where(x => x.AttributeClass is not null && GetTypeFullName(x.AttributeClass) == PartialAttributeFullTypeName)
            .SelectMany(GetPropertiesFromPartialSource);

        return new()
        {
            Namespace = GetNamespace(targetSymbol),
            Name = targetSymbol.Name,
            IsRecord = targetSymbol.IsRecord,
            SourceTypeProperties = sourceTypeProperties,
            ExistingMemberNames = targetSymbol.GetMembers().Select(x => x.Name),
        };        
    }

    private static IEnumerable<IPropertySymbol>? GetPropertiesFromPartialSource(AttributeData attributeData)
    {
        var baseType = attributeData.AttributeClass?.TypeArguments.FirstOrDefault();

        // baseType should never be null, but just in case we'll check for it and propagate the nullability
        return baseType?.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(x => x.DeclaredAccessibility is Accessibility.Public);
    }

    private static string GetTypeFullName(INamedTypeSymbol symbol)
    {
        var aritySuffix = symbol.Arity > 0 ? $"`{symbol.Arity}" : string.Empty;
        return GetNamespace(symbol) + "." + symbol.Name + aritySuffix;
    }

    private static string GetNamespace(ISymbol symbol)
    {
        return string.Join(".", GetAllNamespaces(symbol)
            .Where(static x => !string.IsNullOrWhiteSpace(x.Name))
            .Reverse()
            .Select(static x => x.Name));
    }

    private static IEnumerable<INamespaceSymbol> GetAllNamespaces(ISymbol symbol)
    {
        var currentNamespace = symbol.ContainingNamespace;
        while (currentNamespace is not null)
        {
            yield return currentNamespace;
            currentNamespace = currentNamespace.ContainingNamespace;
        }
    }

    private static void Execute(SourceProductionContext context, PartialClassToGenerate? classToGenerate)
    {
        if (classToGenerate is null)
        {
            return;
        }

        var result = GeneratePartialClass(classToGenerate);
        context.AddSource($"{classToGenerate.Name}.g.cs", SourceText.From(result, Encoding.UTF8));
    }

    private static string GeneratePartialClass(PartialClassToGenerate partialClassToGenerate)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {partialClassToGenerate.Namespace}");
        sb.AppendLine("{");
        var definitionType = partialClassToGenerate.IsRecord ? "record" : "class";
        sb.AppendLine($"    public partial {definitionType} {partialClassToGenerate.Name}");
        sb.AppendLine("    {");
        var usedProperties = new HashSet<string>(partialClassToGenerate.ExistingMemberNames);
        foreach (var propertySymbol in partialClassToGenerate.SourceTypeProperties)
        {
            if (!usedProperties.Add(propertySymbol.Name))
            {
                continue;
            }

            sb.Append("        public ");
            sb.Append("RescueTube.Core.Utils.")
                .Append(propertySymbol.Type switch
                {
                    { IsReferenceType: true, NullableAnnotation: NullableAnnotation.NotAnnotated } => "OptionalClass<" + propertySymbol.Type.ToDisplayString(),
                    { IsReferenceType: true } => "OptionalNullableClass<" + propertySymbol.Type.ToDisplayString().TrimEnd('?'),
                    { IsReferenceType: false } => "OptionalStruct<" + propertySymbol.Type.ToDisplayString(),
                })
                .Append("> ");
            sb.Append(propertySymbol.Name);
            sb.Append(" { get; ");
            if (!propertySymbol.IsReadOnly)
            {
                sb.Append(propertySymbol.SetMethod?.IsInitOnly switch
                {
                    true => "init; ",
                    _ => "set; ",
                });
            }
            sb.Append('}').AppendLine();
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

internal record PartialClassToGenerate
{
    public string Namespace { get; set; } = null!;
    public string Name { get; set; } = null!;
    public bool IsRecord { get; set; }
    public IEnumerable<IPropertySymbol> SourceTypeProperties { get; set; } = null!;
    public IEnumerable<string> ExistingMemberNames { get; set; } = null!;
}
