name: PR validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        dotnet-version: [10]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Use .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          cache: true
          cache-dependency-path: "./**/packages.lock.json"
      
      - name: Run tests
        run: dotnet test -c Release --timeout 2m